# Generated by Django 4.0.2 on 2022-04-30 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FiletoScan',
            new_name='FilestoScan',
        ),
    ]
